### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by stdoo** [UWSysLab/NOPaxos#1]
Hi,
I have created a single topo with 3 hosts in mininet to run the spec, VR and unreplicated mode in this repo. H1 is client and the other two are replicas. After the client started, there is some information shown on the xterm, which makes me confused. It's like this:
![spec](https://cloud.githubusercontent.com/assets/18691008/25887634/78e81b8e-3595-11e7-8833-351e390ebcb8.png)
What does the 22 us 25us/16 us 132 us means?
What does the 16us 32us/65us 131us means?

**Comment by JLin-Li** [comment]
First of all, you should probably create 3 replicas so that they can tolerate 1 node failure. 2 replicas doesn’t make too much sense.

On the "LATENCY total” line:
22 us — minimum latency
25 us — average latency
16 us — median latency
132 us — maximum latency

And the last few lines are the latency histogram. So for example in this case, 95 requests finished between 16-32us, 5 requests finished between 32-65us, etc.

**Comment by stdoo** [comment]
Thanks very much.
